[package]
name = "linear_collections"
version = "0.2.2"
edition = "2021"
description = "Map and Set types backed by linear data structures."
license = "MIT"
repository = "https://github.com/Jeremiah-Griffin/linear_collections"

[dependencies]
serde = { version = "1.*.*", optional = true, default-features = false, features = ["std"]}

[features]
default = []
#Adds support for ser/deserialization with serde.
serde = ["dep:serde"]
