[workspace]
members = ["macros"]

[package]
name = "linear_collections"
version = "0.2.3"
edition = "2021"
description = "Map and Set types backed by linear data structures."
license = "MIT"
repository = "https://github.com/Jeremiah-Griffin/linear_collections"
categories = ["data-structures"]
keywords = ["vecmap", "arraymap", "linearmap", "vecset", "arrayset"]

[dependencies]
serde = { version = "1.*.*", optional = true, default-features = false, features = ["std"]}
macros = {path = "macros", optional = true}

[features]
default = ["macros"]
#Adds support for ser/deserialization with serde.
serde = ["dep:serde"]
#Linear-collections can use macros to validate literals structures at compile time. 
#These add a number of dependencies and are thusly feature gated.
macros = ["dep:macros"]
