///The MapPsuedoArray relies on it being a truly unique referent
///to its backing map. If another thread - even in a synchronized manner - shrinks
///the remaining capacity of the underlying collection, insertion via the MapPsuedoArray
///may cause an out of bounds write, Undefined Behavior.
///
///Consider below:
///
///```
/// pub struct NotSyncMap{
///    inner: Arc<Mutex<SomeMap<K,V>>>
/// }
///
/// impl !Sync for NotSyncMap{}
///
/// impl <K,V>NotSyncMap<K,V>{
///    fn clone(&self) -> NotSyncMap<K,V>{
///       NotSyncMap{
///         inner: self.inner.clone(),
///       }
///    }
/// }
///
///
///```
///As above, `NotSyncMap` is both `!Sync` and permits *interleaved* mutation of
///the underlying `SomeMap`; if a parent thread holds a `MapPsuedoArray<const REMAINING: usize>` of a `NotSyncMap`,
///and a child `NotSyncMap` generated by calling `clone` on its parent's, the child could `shrink` the `NotSyncMap`
///while the `MapPsuedoArray` "thinks" it has `REMAINING` slots left to push. 
/// 
///Thus, this trait serves to mark types which the developer guarantees provide no interface to permit
///interleaved mutation. This must necessarily preclude types which are `Sync`.
///
/// SAFETY: implementors must both not be Sync and not permit interleaved writes. Undefined Behavior will occur if this is not upheld.pub unsafe trait NoInterleavedMutation{}
pub unsafe trait NoInterleavedMutation{}
