mod psuedo_array {
    use std::marker::PhantomData;

    use crate::{Map, Set};

    ///add one with a standard error message.
    const fn remaining_add_one<const REMAINING: usize>() -> usize {
        //TODO: shouldn't this be isize? Review implementations.
        REMAINING
            .checked_add(1)
            .expect("REMAINING must less than usize::MAX")
    }
    ///subtract one with a standard error message.
    const fn remaining_sub_one<const REMAINING: usize>() -> usize {
        REMAINING
            .checked_sub(1)
            .expect("REMAINING must less than usize::MAX")
    }

    ///A psuedo array is a type which provides
    ///for certain infallible mutations when a collection has
    ///been grown by a constant factor.
    pub struct PsuedoArray<
        'collection,
        Item,
        Collection: PsuedoArrayProvider<Item>,
        const REMAINING: usize,
    > {
        inner: &'collection mut Collection,
        phantom: PhantomData<Item>,
    }

    ///SAFETY:
    ///It must be guaranteed that the implementor does not permit interleaved mutation. This means the type is both *not* sync
    ///
    ///
    ///The MapPsuedoArray relies on it being a truly unique referent
    ///to its backing map. If another thread - even in a synchronized manner - shrinks
    ///the remaining capacity of the underlying collection, insertion via the MapPsuedoArray
    ///may cause an out of bounds write, Undefined Behavior.
    ///
    ///Consider below:
    ///
    ///```ignore
    /// pub struct NotSyncMap<K,V>{
    ///    inner: Arc<Mutex<SomeMap<K,V>>>
    /// }
    ///
    /// impl<K,V> !Sync for NotSyncMap<K,V>{}
    ///
    /// impl <K,V>NotSyncMap<K,V>{
    ///    fn clone(&self) -> NotSyncMap<K,V>{
    ///       NotSyncMap{
    ///         inner: self.inner.clone(),
    ///       }
    ///    }
    /// }
    ///
    ///
    ///```
    ///As above, `NotSyncMap` is both `!Sync` and permits *interleaved* mutation of
    ///the underlying `SomeMap`; if a parent thread holds a `MapPsuedoArray<const REMAINING: usize>` of a `NotSyncMap`,
    ///and a child `NotSyncMap` generated by calling `clone` on its parent's, the child could `shrink` the `NotSyncMap`
    ///while the `MapPsuedoArray` "thinks" it has `REMAINING` slots left to push.
    ///
    ///Thus, this trait serves to mark types which the developer guarantees provide no interface to permit
    ///interleaved mutation. This must necessarily preclude types which are `Sync`.
    ///
    ///
    /// Presently, this is a sealed trait due to this restriction, but this mayh be relaxed in the future.
    pub(crate) unsafe trait PsuedoArrayProvider<Item> {
        ///The error type used by the backing collection
        type Error: std::error::Error;
    }

    impl<'collection, Item, Collection: PsuedoArrayProvider<Item>, const REMAINING: usize>
        PsuedoArray<'collection, Item, Collection, REMAINING>
    {
    }

    impl<
        'collection,
        Key: Eq,
        Value,
        Collection: PsuedoArrayProvider<(Key, Value)> + Map<Key, Value>,
        const REMAINING: usize,
    > PsuedoArray<'collection, (Key, Value), Collection, REMAINING>
    where
        [(); remaining_sub_one::<REMAINING>()]:,
    {
    }

    impl<
        'collection,
        Item: Eq,
        Collection: PsuedoArrayProvider<Item> + Set<Item>,
        const REMAINING: usize,
    > PsuedoArray<'collection, Item, Collection, REMAINING>
    where
        [(); remaining_sub_one::<REMAINING>()]:,
    {
    }

    ///In the case of a call to `remove` which returns `Some` a MapPsuedoArray will have an additional unit of capacity
    /// Otherwise, its capacity will stay the same. This enum is used to reflect this.
    pub enum RemoveResult<
        'collection,
        Item,
        Collection: PsuedoArrayProvider<Item>,
        const REMAINING: usize,
    >
    where
        [(); remaining_add_one::<REMAINING>()]:,
    {
        Found {
            psuedo_array:
                PsuedoArray<'collection, Item, Collection, { remaining_add_one::<REMAINING>() }>,
            value: Item,
        },
        NotFound(PsuedoArray<'collection, Item, Collection, REMAINING>),
    }

    pub enum MapRemoveResult<
        'collection,
        Key: Eq,
        Value,
        Collection: PsuedoArrayProvider<(Key, Value)>,
        const REMAINING: usize,
    >
    where
        [(); remaining_add_one::<REMAINING>()]:,
    {
        Found {
            psuedo_array: PsuedoArray<
                'collection,
                (Key, Value),
                Collection,
                { remaining_add_one::<REMAINING>() },
            >,
        },
    }
}

mod binary {}
